### ISSUE TITLE
Documentation fixes for API changes

### ISSUE THREAD

**Issue by mattjshannon** [PAHdb/pyPAHdb#14]
General doc updates needed:
- Update intro/usage for changes in API (remove writer reference and replace with save_xxx, class names etc.)
- Update academic reference(s), little subsections, Bibtex entries?

In tutorial notebooks:
- Updated class names/imports.
- Funny line-break (tutorial 1).
- Reference the Spitzer spectrum (Boersma+ 2012?)
- Update for recent changes, i.e., capitalize class names and remove writer-class.
- Incorporate some aesthetic changes (based on astropy tutorials).

**Comment by PAHdb** [comment]
Issue addressed in #13.
