### ISSUE TITLE
Possible performance issues?

### ISSUE THREAD

**Issue by mattjshannon** [PAHdb/pyPAHdb#15]
Qualitatively, running tutorial 1 (with the API changes of `decomposer.py`) seems like it might have lost some performance. @PAHdb, would you be able to benchmark pyPAHdb using the same data/parameters as was done for the conference proceeding? Just to see if the numbers still line up. Thanks.

**Comment by PAHdb** [comment]
The issue is having all the multiprocessing-functions inside the class. You should move them outside the class again, i.e., _decomposer_interp, etc. Don't forget to remove the 'self'.

**Comment by mattjshannon** [comment]
> The issue is having all the multiprocessing-functions inside the class. You should move them outside the class again, i.e., _decomposer_interp, etc. Don't forget to remove the 'self'.

Interesting, do you know why that causes a performance difference? Naively I wouldn't have expected it. Will correct this tomorrow, thanks!

**Comment by PAHdb** [comment]
I haven't confirmed this, but my suspicion would be that the class-references need to be resolved each time in the main thread, i.e., the 'self' in Array(self, function) needs to be resolved on each call, while having it outside the class avoids needing to 'find' self each time.

**Comment by mattjshannon** [comment]
> I haven't confirmed this, but my suspicion would be that the class-references need to be resolved each time in the main thread, i.e., the 'self' in Array(self, function) needs to be resolved on each call, while having it outside the class avoids needing to 'find' self each time.

I think you must be right. That fixed the issue. I'll bundle it up with some other improvements/fixes later (likely improving the unit tests and whatever else is on the to-do list).

This reminds me that we should add a TODO to the list: code profiling. We might be able to optimize its operation further. I'll add an issue to this effect.

**Comment by PAHdb** [comment]
Pull Request #17 fixes the issue.
