### ISSUE TITLE
Update package requirements

### ISSUE THREAD

**Issue by mattjshannon** [PAHdb/pyPAHdb#2]
We should determine what the minimum version numbers are for the required modules (e.g., numpy, scipy). I imagine there's a reasonably simple way of doing this.

**Comment by PAHdb** [comment]
scipy and matplotlib will have numpy as a dependency, so we should be careful we don't over-qualify the dependencies. Possibly requiring astropy covers most dependencies ...

**Comment by mattjshannon** [comment]
Since there were no issues at Les Houches, let's close this.
