### ISSUE TITLE
Add Class Inheritance Diagram to the docs

### ISSUE THREAD

**Issue by PAHdb** [PAHdb/pyPAHdb#25]
Add Class Inheritance Diagram via :automodapi: -- see https://www.google.com/url?q=https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html

**Comment by mattjshannon** [comment]
For example, see figure at bottom of this page: https://pahfit.readthedocs.io/en/latest/?badge=latest

Few options to do this:
- https://github.com/astropy/sphinx-automodapi
- https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html

**Comment by PAHdb** [comment]
Diagram added, closing issue.
