### ISSUE TITLE
Not Able to Install in Windows

### ISSUE THREAD

**Issue by ElricPi** [PAHdb/pyPAHdb#36]
Hi, I tried to install this code in my windows machine with all the necessary requirements but it is making the following error (attached). Please let me know if anything can be done. 

Thank You.

<img width="960" alt="2021-08-04 (11)" src="https://user-images.githubusercontent.com/72200932/128123287-822200a0-994a-42b8-9e93-d14c352336bc.png">

**Comment by alexmaragko** [comment]
Hi. Did you try installing from the terminal within a conda environment, instead of a jupyter notebook?
Alternatively, could you clone the repository, cd into the directory and run `pip install -e .` and see if that works?

**Comment by ElricPi** [comment]
Hello, thank you for the suggestions, I carried them out but the errors still remain. I tried a couple of ways to install it, so I have attached screenshots for your perusal. Please guide me on what to do next. Also I think all of these give the same error output.

Thank You.

![image](https://user-images.githubusercontent.com/72200932/128346475-01af50f0-a449-42e0-b305-2eef5d0e8885.png)


![image](https://user-images.githubusercontent.com/72200932/128346506-1a1da37c-8b43-48e6-a9dd-3ded8afe41a5.png)

![image](https://user-images.githubusercontent.com/72200932/128346972-b4421a6f-3e96-4a1d-83bd-e6bf9b9b0b13.png)

![image](https://user-images.githubusercontent.com/72200932/128347354-a06e6f02-c98c-4b5c-819c-cfaa8eb53025.png)

**Comment by alexmaragko** [comment]
Hi. It seems there is an issue decoding non-ASCII characters in your machine. We have removed certain non-ASCII double quotes in the README.md that could have caused this. We made a successful installation on a Windows 10 machine under Python 3 without encountering any issues. 
Could you try now to make a fresh install, deleting any previous pypahdb directories? If this still persists, maybe you could try to delete the contents of the README.md file and try again. Thank you for looking into this.

**Comment by ElricPi** [comment]
Thank You so much for the help. It was a life saver! It got installed perfectly this time.
