### ISSUE TITLE
Issues with installing pyPAHdb

### ISSUE THREAD

**Issue by dubeydwaipayan** [PAHdb/pyPAHdb#38]
![image](https://user-images.githubusercontent.com/73394996/138274048-b5d05d50-4edc-4089-86f1-b46f9148e522.png)

**Comment by alexmaragko** [comment]
Hi. It seems you are getting an error of being unable to connect to github.com. Make sure you are not under a firewall, otherwise try downloading the code and install it on your machine. If everything else fails, perhaps you could share the logs created, as stated in the screenshot you provided.

**Comment by PAHdb** [comment]
Assuming resolved due to lack of feedback.
