### ISSUE TITLE
Git Large File Storage GitHub Bandwidth

### ISSUE THREAD

**Issue by PAHdb** [PAHdb/pyPAHdb#5]
The free-tier lfs-storage at GitHub only offers 1Gb/month bandwidth - saturating the quota with only four downloads of the precomputed matrix.

There are three solutions to this:
  1. Pay GitHub $5/month for a bandwidth of 50Gb/month
  2. Update the python code to download the precomputed matrix from the astrochemistry-domain upon first usage
  3. Setup a lfs-server at astrochemistry - one implementation that seems straightforward, allows HTTPS and authentication is by [artemkin](https://github.com/artemkin/git-lfs-server)

**Comment by mattjshannon** [comment]
As we've settled on option 2, should we close this issue?

**Comment by PAHdb** [comment]
After trying option 3. for a while, it became clear that too many credential issues needed to be overcome to make it work for everyone. While now an approach is used that seems most similar to 2., it is more like 2b. as the downloading of the precomputed matrix is moved into the py_build-phase.

This closes the issue.
